version: '3.5'

services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - "8998:8000"
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
